alias .='pwd'
alias so='source'
alias c='clear'
alias g='grep'
alias h='history'
alias l='less'
alias la='ls -a'
alias ltr='ls -ltr'
alias ltra='ls -ltra'
alias py='python'
alias aliaser='source .myalias.sh'
alias maker='c; opp_makemake -f; make'
alias runner='c; Distributed_SFC_migration.exe &'

