//
// Generated file, do not edit! Created by nedtool 5.6 from RunTraceSelvMsg.msg.
//

#ifndef __RUNTRACESELVMSG_M_H
#define __RUNTRACESELVMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>RunTraceSelvMsg.msg:3</tt> by nedtool.
 * <pre>
 * // A self-msg of SimController to start reading the trace and simulate, after all initializations are done
 * message RunTraceSelfMsg
 * {
 * }
 * </pre>
 */
class RunTraceSelfMsg : public ::omnetpp::cMessage
{
  protected:

  private:
    void copy(const RunTraceSelfMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RunTraceSelfMsg&);

  public:
    RunTraceSelfMsg(const char *name=nullptr, short kind=0);
    RunTraceSelfMsg(const RunTraceSelfMsg& other);
    virtual ~RunTraceSelfMsg();
    RunTraceSelfMsg& operator=(const RunTraceSelfMsg& other);
    virtual RunTraceSelfMsg *dup() const override {return new RunTraceSelfMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RunTraceSelfMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RunTraceSelfMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __RUNTRACESELVMSG_M_H

