//
// Generated file, do not edit! Created by nedtool 5.7 from src/bottomUpPkt.msg.
//

#ifndef __BOTTOMUPPKT_M_H
#define __BOTTOMUPPKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#pragma once
#include "Chain.h"
// }}

/**
 * Class generated from <tt>src/bottomUpPkt.msg:10</tt> by nedtool.
 * <pre>
 * packet bottomUpPkt
 * {
 * }
 * </pre>
 */
class bottomUpPkt : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const bottomUpPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const bottomUpPkt&);

  public:
    bottomUpPkt(const char *name=nullptr, short kind=0);
    bottomUpPkt(const bottomUpPkt& other);
    virtual ~bottomUpPkt();
    bottomUpPkt& operator=(const bottomUpPkt& other);
    virtual bottomUpPkt *dup() const override {return new bottomUpPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const bottomUpPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, bottomUpPkt& obj) {obj.parsimUnpack(b);}


#endif // ifndef __BOTTOMUPPKT_M_H

