//
// Generated file, do not edit! Created by nedtool 5.6 from InitBottomUpMsg.msg.
//

#ifndef __INITBOTTOMUPMSG_M_H
#define __INITBOTTOMUPMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#pragma once
#include "Chain.h"
// }}

/**
 * Class generated from <tt>InitBottomUpMsg.msg:12</tt> by nedtool.
 * <pre>
 * message InitBottomUpMsg
 * {
 *     Chain notAssigned[]; // new or critical chains to be assigned 
 * }
 * </pre>
 */
class InitBottomUpMsg : public ::omnetpp::cMessage
{
  protected:
    Chain *notAssigned; // array ptr
    unsigned int notAssigned_arraysize;

  private:
    void copy(const InitBottomUpMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const InitBottomUpMsg&);

  public:
    InitBottomUpMsg(const char *name=nullptr, short kind=0);
    InitBottomUpMsg(const InitBottomUpMsg& other);
    virtual ~InitBottomUpMsg();
    InitBottomUpMsg& operator=(const InitBottomUpMsg& other);
    virtual InitBottomUpMsg *dup() const override {return new InitBottomUpMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual void setNotAssignedArraySize(unsigned int size);
    virtual unsigned int getNotAssignedArraySize() const;
    virtual Chain& getNotAssigned(unsigned int k);
    virtual const Chain& getNotAssigned(unsigned int k) const {return const_cast<InitBottomUpMsg*>(this)->getNotAssigned(k);}
    virtual void setNotAssigned(unsigned int k, const Chain& notAssigned);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const InitBottomUpMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, InitBottomUpMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __INITBOTTOMUPMSG_M_H

