//
// Generated file, do not edit! Created by nedtool 5.6 from prepareReshDownSyncPkt.msg.
//

#ifndef __PREPARERESHDOWNSYNCPKT_M_H
#define __PREPARERESHDOWNSYNCPKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#pragma once
#include "Chain.h"
// }}

/**
 * Class generated from <tt>prepareReshDownSyncPkt.msg:9</tt> by nedtool.
 * <pre>
 * packet prepareReshSyncDownPkt
 * {
 *     Chain notAssigned[];
 * }
 * </pre>
 */
class prepareReshSyncDownPkt : public ::omnetpp::cPacket
{
  protected:
    Chain *notAssigned; // array ptr
    unsigned int notAssigned_arraysize;

  private:
    void copy(const prepareReshSyncDownPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const prepareReshSyncDownPkt&);

  public:
    prepareReshSyncDownPkt(const char *name=nullptr, short kind=0);
    prepareReshSyncDownPkt(const prepareReshSyncDownPkt& other);
    virtual ~prepareReshSyncDownPkt();
    prepareReshSyncDownPkt& operator=(const prepareReshSyncDownPkt& other);
    virtual prepareReshSyncDownPkt *dup() const override {return new prepareReshSyncDownPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual void setNotAssignedArraySize(unsigned int size);
    virtual unsigned int getNotAssignedArraySize() const;
    virtual Chain& getNotAssigned(unsigned int k);
    virtual const Chain& getNotAssigned(unsigned int k) const {return const_cast<prepareReshSyncDownPkt*>(this)->getNotAssigned(k);}
    virtual void setNotAssigned(unsigned int k, const Chain& notAssigned);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const prepareReshSyncDownPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, prepareReshSyncDownPkt& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PREPARERESHDOWNSYNCPKT_M_H

