//
// Generated file, do not edit! Created by nedtool 5.6 from prepareReshUpSyncPkt.msg.
//

#ifndef __PREPARERESHUPSYNCPKT_M_H
#define __PREPARERESHUPSYNCPKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>prepareReshUpSyncPkt.msg:3</tt> by nedtool.
 * <pre>
 * packet PrepareReshUpSyncPkt
 * {
 * }
 * </pre>
 */
class PrepareReshUpSyncPkt : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const PrepareReshUpSyncPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PrepareReshUpSyncPkt&);

  public:
    PrepareReshUpSyncPkt(const char *name=nullptr, short kind=0);
    PrepareReshUpSyncPkt(const PrepareReshUpSyncPkt& other);
    virtual ~PrepareReshUpSyncPkt();
    PrepareReshUpSyncPkt& operator=(const PrepareReshUpSyncPkt& other);
    virtual PrepareReshUpSyncPkt *dup() const override {return new PrepareReshUpSyncPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PrepareReshUpSyncPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PrepareReshUpSyncPkt& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PREPARERESHUPSYNCPKT_M_H

