//
// Generated file, do not edit! Created by nedtool 5.7 from src/prepareReshuffle.msg.
//

#ifndef __PREPARERESHUFFLE_M_H
#define __PREPARERESHUFFLE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/prepareReshuffle.msg:2</tt> by nedtool.
 * <pre>
 * packet prepareReshuffle
 * {
 * }
 * </pre>
 */
class prepareReshuffle : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const prepareReshuffle& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const prepareReshuffle&);

  public:
    prepareReshuffle(const char *name=nullptr, short kind=0);
    prepareReshuffle(const prepareReshuffle& other);
    virtual ~prepareReshuffle();
    prepareReshuffle& operator=(const prepareReshuffle& other);
    virtual prepareReshuffle *dup() const override {return new prepareReshuffle(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const prepareReshuffle& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, prepareReshuffle& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PREPARERESHUFFLE_M_H

