//
// Generated file, do not edit! Created by nedtool 5.6 from prepareReshufflePkt.msg.
//

#ifndef __PREPARERESHUFFLEPKT_M_H
#define __PREPARERESHUFFLEPKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>prepareReshufflePkt.msg:1</tt> by nedtool.
 * <pre>
 * packet PrepareReshufflePkt
 * {
 * }
 * </pre>
 */
class PrepareReshufflePkt : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const PrepareReshufflePkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PrepareReshufflePkt&);

  public:
    PrepareReshufflePkt(const char *name=nullptr, short kind=0);
    PrepareReshufflePkt(const PrepareReshufflePkt& other);
    virtual ~PrepareReshufflePkt();
    PrepareReshufflePkt& operator=(const PrepareReshufflePkt& other);
    virtual PrepareReshufflePkt *dup() const override {return new PrepareReshufflePkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PrepareReshufflePkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PrepareReshufflePkt& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PREPARERESHUFFLEPKT_M_H

