package src;

//
// Central controller of the simulation. Does the following:
// - Read the input files, showing users' mobility, and calls the leaf datacenters to place new/migrated chains accordingly.
//

simple TraceFeeder
{
    parameters:
        @display("i=misc/node_vs,gold");

//    private:
//        virtual void initialize();
//        virtual void handleMessage (cMessage *msg);
    
        
}